version: "3.7"

services:
  backend:
    build:
      context: "./Backend"
    environment:
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000

    ports:
      - "5000:5000"
  frontend:
    build:
      context: "./Frontend"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./Frontend:/app
      - /app/node_modules

    ports:
      - "3000:5173"
    command: npm run dev
