version: "3.7"

services:
  backend:
    build:
      context: "./backend"
    environment:
      - PORT=${PORT}
      - URL=${URL}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start

  frontend:
    build:
      context: "./frontend"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
